version: '3.5'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: mm#236533
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - voting-network
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: 'voting'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'mm#236533'
      MYSQL_ROOT_PASSWORD: 'mm#236533'
    ports:
      - 3306:3306
    networks:
      - voting-network
    volumes:
      - ./mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 7777:8080
    networks:
      - voting-network
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql-server
      ADMINER_DEFAULT_USERNAME: admin
      ADMINER_DEFAULT_PASSWORD: mm#236533
      ADMINER_DEFAULT_DATABASE: voting

  voting-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - voting-network
    depends_on:
      - mysql
      - rabbitmq
    environment:
      - spring.application.name=voting-service
      - spring.datasource.url=jdbc:mysql://mysql:3306/voting?sslMode=REQUIRED
      - spring.datasource.username=admin
      - spring.datasource.password=mm#236533
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.generate-ddl=true
      - spring.jpa.show-sql=true
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=admin
      - spring.rabbitmq.password=mm#236533
      - spring.rabbitmq.queue-name=votingQueue

volumes:
  mysql-db:
  rabbitmq-data:

networks:
  voting-network: